#!/usr/bin/env php
<?php
/**
 * Yii command line script for Unix/Linux.
 *
 * This is the bootstrap script for running yiic on Unix/Linux.
 *
 * @author Qiang Xue <qiang.xue@gmail.com>
 * @link http://www.yiiframework.com/
 * @copyright 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

$yiic = dirname(__FILE__).'/../framework/yiic.php';
$config=dirname(__FILE__).'/protected/config/console.php';
@putenv('YII_CONSOLE_COMMANDS='. dirname(__FILE__).'/protected/commands' );
require_once($yiic);
